{application, audit_log,
    [{description, "Audit Log"},
     {vsn, "2.5.0"},
     {modules,
         [audit_log_app,
          audit_log_ctrl,
          audit_log_disk,
          audit_log_disk_sup,
          audit_log,
          audit_log_i,
          audit_log_lib,
          audit_log_sup]},
     {registered, [audit_log_ctrl]},
     {mod, {audit_log_app, []}},
     {applications, [kernel, stdlib, mnesia]}
    ]}.
